version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/AdvaRisk
    ports:
      - "8000:8000"
    depends_on:
      - db