# Generated by Django 3.1.1 on 2020-09-03 16:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('helpfulness', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('summary', models.CharField(max_length=500)),
                ('text', models.TextField(max_length=2000)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_gin_idx'),
        ),
    ]
