# Generated by Django 3.1.1 on 2020-09-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200903_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
